#!/bin/sh
#
# Run the malloc program for a set of sample traces.
# Note that this has to use zsh for floating point
# -- Dirk Grunwald
#
TRACES="binary2-bal.rep coalescing-bal.rep random2-bal.rep \
  realloc-bal.rep binary-bal.rep cp-decl-bal.rep random-bal.rep \
  short1-bal.rep cccp-bal.rep expr-bal.rep realloc2-bal.rep  short2-bal.rep"


PROGRAM="./mdriver"
if [ "$*" != "" ] ;
then
  PROGRAM="$1"
else
  make clean
  make -j4
fi
  
OUTPUT=/tmp/OUT$$
sum=0
samples=0
tries=0
for trace in $TRACES ;
do
       echo "          ----------------"
       if $PROGRAM -a -f ./traces/$trace > $OUTPUT ;
       then  
	       echo "Trace: $trace"	
	       cat $OUTPUT
	       value=`sed -n -e 's/.* \([0-9][0-9]*\)\/100/\1/p' $OUTPUT`
	       if [ "X$value" = "X" ];
	       then
		   echo "Unable to extract score from this run"
	       else
		   sum=`expr $sum + $value`
		   samples=`expr $samples + 1`
	       fi	 
	       tries=`expr $tries + 1`

       else
	       echo "--Trace: $trace Failed"
       fi
done

echo ""
echo "-----------------------------------------------------------------------------"
echo "For program $PROGRAM"
echo "sum is $sum, samples is $samples"
score=$(echo "print $sum/$samples if $samples >0 else 0" | python)
grade=$(echo "print min(110,-134. + $score * 2.8)" | python)
missed=`expr $tries - $samples`
echo "Average Score is $score with $missed missed cases for grade of $grade"
echo "-----------------------------------------------------------------------------"
